version: 0.2

env:
    variables:
        AWS_REGION: "ap-southeast-1"
        ECR_REPOSITORY: "891377055161.dkr.ecr.ap-southeast-1.amazonaws.com/dva-nodejs-app-demo"

phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "Build images to ECR"
    pre_build:
        commands:
            - echo "Logging into Amazon ECR..."
            - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 891377055161.dkr.ecr.ap-southeast-1.amazonaws.com
    build:
        commands:
            - echo "Building Docker image..."
            - docker build -t dva-nodejs-app-demo .
            - docker tag dva-nodejs-app-demo:latest 891377055161.dkr.ecr.ap-southeast-1.amazonaws.com/dva-nodejs-app-demo:latest
    post_build:
        commands:
            - echo "Pushing Docker image to Amazon ECR..."
            - docker push 891377055161.dkr.ecr.ap-southeast-1.amazonaws.com/dva-nodejs-app-demo:latest
            - echo "Build completed successfully!"
artifacts:
 files: dvanodejs.json
